name: ci
on: push


jobs:
  build_publish_docker_hub:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
          name: Check out code
      
        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
            image: ${{ secrets.DOCKERHUB_USERNAME }}/car-app3
            tags: v1, latest
            registry: docker.io
            dockerfile: Dockerfile
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}